import type { CoachCue } from "./coach";

export const cueDefaults = {
  minimumSpeechGapMs: 6_000,
  recentHistorySize: 3,
  minimumPoseConfidence: 0.72,
} as const;

// Canonical English scripts from MICHAEL_COACH_CUE_LIBRARY.v1.
// Spanish UI is available, but these lines stay untranslated until Michael's
// Spanish voice and the translated cue library receive explicit approval.
export const michaelCoachCues: CoachCue[] = [
  { id: "session-welcome-01", exercise: "*", event: "session.started", intent: "welcome", tone: "calm", text: "Hey, it’s Michael. I’m right here with you. Let’s make this a strong session.", priority: 70, weight: 1, cooldownMs: 0, maxUsesPerSession: 1, minConfidence: 0, interruptible: true, assetKey: "michael-v1.en.dark-coach-v1.session-welcome-01", tags: ["session", "welcome"] },
  { id: "camera-step-back-01", exercise: "*", event: "camera.body_too_close", intent: "camera_setup", tone: "calm", text: "Take one small step back so I can see your full movement.", priority: 90, weight: 1, cooldownMs: 10_000, maxUsesPerSession: 3, minConfidence: 0.45, interruptible: true, assetKey: "michael-v1.en.dark-coach-v1.camera-step-back-01", tags: ["camera", "framing"] },
  { id: "camera-full-body-01", exercise: "*", event: "camera.body_clipped", intent: "camera_setup", tone: "calm", text: "Adjust the camera so your head and feet stay in the frame.", priority: 90, weight: 1, cooldownMs: 10_000, maxUsesPerSession: 3, minConfidence: 0.35, interruptible: true, assetKey: "michael-v1.en.dark-coach-v1.camera-full-body-01", tags: ["camera", "framing"] },
  { id: "camera-recovered-01", exercise: "*", event: "camera.tracking_recovered", intent: "camera_confirmation", tone: "calm", text: "Perfect, I’ve got you again. Continue when you’re ready.", priority: 70, weight: 1, cooldownMs: 10_000, maxUsesPerSession: 2, minConfidence: 0.72, interruptible: true, assetKey: "michael-v1.en.dark-coach-v1.camera-recovered-01", tags: ["camera", "recovered"] },
  { id: "encourage-almost-there-01", exercise: "*", event: "set.final_reps", intent: "final_reps", tone: "push", text: "Come on, you’re almost there. Finish these last reps with me.", priority: 70, weight: 1, cooldownMs: 0, maxUsesPerSession: 3, minConfidence: 0.72, interruptible: false, assetKey: "michael-v1.en.dark-coach-v1.encourage-almost-there-01", tags: ["encouragement", "final-reps"] },
  { id: "encourage-two-more-01", exercise: "*", event: "set.two_reps_remaining", intent: "final_reps", tone: "push", text: "Two more. Make them clean and strong.", priority: 70, weight: 1, cooldownMs: 0, maxUsesPerSession: 3, minConfidence: 0.72, interruptible: false, assetKey: "michael-v1.en.dark-coach-v1.encourage-two-more-01", tags: ["encouragement", "final-reps"] },
  { id: "encourage-last-one-01", exercise: "*", event: "set.last_rep", intent: "final_rep", tone: "push", text: "Last one. Control it all the way through.", priority: 70, weight: 1, cooldownMs: 0, maxUsesPerSession: 3, minConfidence: 0.72, interruptible: false, assetKey: "michael-v1.en.dark-coach-v1.encourage-last-one-01", tags: ["encouragement", "final-rep"] },
  { id: "safety-stop-pain-01", exercise: "*", event: "safety.pain_reported", intent: "safety_stop", tone: "safety", text: "Stop there. If you feel sharp pain, don’t push through it.", priority: 100, weight: 1, cooldownMs: 0, maxUsesPerSession: 5, minConfidence: 0, interruptible: false, assetKey: "michael-v1.en.dark-coach-v1.safety-stop-pain-01", tags: ["safety", "stop"] },
  { id: "safety-lost-balance-01", exercise: "*", event: "safety.balance_lost", intent: "safety_stop", tone: "safety", text: "Pause and find your balance. Reset before you continue.", priority: 100, weight: 1, cooldownMs: 6_000, maxUsesPerSession: 5, minConfidence: 0.72, interruptible: false, assetKey: "michael-v1.en.dark-coach-v1.safety-lost-balance-01", tags: ["safety", "balance"] },
  { id: "set-complete-01", exercise: "*", event: "set.completed", intent: "set_complete", tone: "coach", text: "Set complete. Nice work—take your recovery.", priority: 70, weight: 1, cooldownMs: 0, maxUsesPerSession: 4, minConfidence: 0, interruptible: false, assetKey: "michael-v1.en.dark-coach-v1.set-complete-01", tags: ["set", "complete"] },
  { id: "rest-complete-01", exercise: "*", event: "rest.completed", intent: "rest_complete", tone: "coach", text: "Rest is over. Let’s bring the same control to this next set.", priority: 70, weight: 1, cooldownMs: 0, maxUsesPerSession: 3, minConfidence: 0, interruptible: false, assetKey: "michael-v1.en.dark-coach-v1.rest-complete-01", tags: ["rest", "complete"] },
  { id: "squat-setup-01", exercise: "squat", event: "exercise.setup", intent: "exercise_setup", tone: "coach", text: "Feet set, chest tall, and brace your core. Sit down and back with control.", priority: 70, weight: 1, cooldownMs: 0, maxUsesPerSession: 1, minConfidence: 0.72, interruptible: true, assetKey: "michael-v1.en.dark-coach-v1.squat-setup-01", tags: ["squat", "setup"] },
  { id: "squat-depth-shallow-01", exercise: "squat", event: "form.depth_shallow", intent: "form_correction", tone: "coach", text: "Good control. Give me a little more depth on the next one.", priority: 80, weight: 1, cooldownMs: 12_000, maxUsesPerSession: 3, minConfidence: 0.78, interruptible: true, conditions: [{ metric: "bottomKneeAngle", operator: ">", value: 110 }], assetKey: "michael-v1.en.dark-coach-v1.squat-depth-shallow-01", tags: ["squat", "depth", "correction"] },
  { id: "squat-knees-in-01", exercise: "squat", event: "form.knees_in", intent: "form_correction", tone: "coach", text: "Press your knees gently out so they track over your toes.", priority: 80, weight: 1, cooldownMs: 12_000, maxUsesPerSession: 3, minConfidence: 0.82, interruptible: true, assetKey: "michael-v1.en.dark-coach-v1.squat-knees-in-01", tags: ["squat", "knees", "correction"] },
  { id: "squat-chest-falling-01", exercise: "squat", event: "form.trunk_lean_excessive", intent: "form_correction", tone: "coach", text: "Lift your chest and keep your core braced as you drive up.", priority: 80, weight: 1, cooldownMs: 12_000, maxUsesPerSession: 3, minConfidence: 0.8, interruptible: true, conditions: [{ metric: "trunkLeanDegrees", operator: ">", value: 45 }], assetKey: "michael-v1.en.dark-coach-v1.squat-chest-falling-01", tags: ["squat", "trunk", "correction"] },
  { id: "squat-heels-up-01", exercise: "squat", event: "form.heels_lifting", intent: "form_correction", tone: "coach", text: "Keep your whole foot connected to the floor, especially the heels.", priority: 80, weight: 1, cooldownMs: 12_000, maxUsesPerSession: 3, minConfidence: 0.8, interruptible: true, assetKey: "michael-v1.en.dark-coach-v1.squat-heels-up-01", tags: ["squat", "heels", "correction"] },
  { id: "squat-stand-tall-01", exercise: "squat", event: "form.incomplete_lockout", intent: "form_correction", tone: "coach", text: "Finish tall at the top, then reset before the next rep.", priority: 80, weight: 1, cooldownMs: 12_000, maxUsesPerSession: 3, minConfidence: 0.78, interruptible: true, assetKey: "michael-v1.en.dark-coach-v1.squat-stand-tall-01", tags: ["squat", "lockout", "correction"] },
  { id: "squat-good-rep-01", exercise: "squat", event: "rep.good", intent: "form_confirmation", tone: "coach", text: "Great squat. Stable, controlled, and strong.", priority: 50, weight: 1, cooldownMs: 16_000, maxUsesPerSession: 2, minConfidence: 0.82, interruptible: true, assetKey: "michael-v1.en.dark-coach-v1.squat-good-rep-01", tags: ["squat", "good-rep"] },
  { id: "encourage-comeback-01", exercise: "*", event: "form.recovered", intent: "recovery_confirmation", tone: "coach", text: "Yes, that’s the adjustment. Keep it there.", priority: 70, weight: 1, cooldownMs: 10_000, maxUsesPerSession: 2, minConfidence: 0.78, interruptible: true, assetKey: "michael-v1.en.dark-coach-v1.encourage-comeback-01", tags: ["encouragement", "recovery"] },
];
