import Link from "next/link";
import { services, solutions } from "@/content/catalog";
import { insights } from "@/content/insights";
import { readTimeLabel } from "@/content/insight-meta";
import { SystemMap } from "./system-map";
import { HomeJsonLd } from "./json-ld";

const copy = {
  en: { eyebrow: "AI implementation for established businesses", title: <>AI that works <em>inside your business.</em></>, lead: "Viste.ai finds the right operational problems, builds controlled AI systems and integrates them into the way your people already work.", primary: "Discuss your use case", secondary: "Explore services", strip: ["Business-first discovery", "Controlled pilots", "Human oversight", "Measurable value"], serviceEyebrow: "Where we help", serviceTitle: "From operational friction to working systems", blueprintEyebrow: "Solution Blueprints", blueprintTitle: "See the system before you buy the promise", blueprintLead: "Concrete examples of what we can design—not invented case studies.", processEyebrow: "A disciplined path", processTitle: "Discover. Design. Pilot. Integrate. Measure.", processLead: "We make the operating case, controls and success measures explicit before technology spreads.", insightEyebrow: "Field notes", insightTitle: "Practical thinking for AI decision-makers", closer: "Where does work get stuck?", closerText: "Bring us the workflow, the constraint and the outcome. We will tell you candidly what a sensible first step looks like." },
  es: { eyebrow: "Implementación de IA para empresas consolidadas", title: <>IA que funciona <em>dentro de tu empresa.</em></>, lead: "Viste.ai identifica los problemas operativos adecuados, construye sistemas de IA controlados y los integra en la forma real de trabajar de tu equipo.", primary: "Cuéntanos tu caso", secondary: "Explorar servicios", strip: ["Diagnóstico de negocio", "Pilotos controlados", "Supervisión humana", "Valor medible"], serviceEyebrow: "Dónde ayudamos", serviceTitle: "De la fricción operativa a sistemas que funcionan", blueprintEyebrow: "Diseños de Solución", blueprintTitle: "Ve el sistema antes de comprar la promesa", blueprintLead: "Ejemplos concretos de lo que podemos diseñar, no casos inventados.", processEyebrow: "Un camino disciplinado", processTitle: "Descubrir. Diseñar. Pilotar. Integrar. Medir.", processLead: "Hacemos explícitos el caso operativo, los controles y las métricas antes de extender la tecnología.", insightEyebrow: "Notas de campo", insightTitle: "Ideas prácticas para decidir sobre IA", closer: "¿Dónde se atasca el trabajo?", closerText: "Trae el flujo, la restricción y el resultado. Te diremos con franqueza cuál es el primer paso sensato." },
};

export function Home({ locale }: { locale: "en" | "es" }) { const c = copy[locale]; const contact = locale === "en" ? "/contact" : "/es/contacto"; const service = locale === "en" ? "/services" : "/es/servicios"; return <main id="body"><HomeJsonLd />
  <section className="home-hero"><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /><div className="shell hero-grid"><div><p className="eyebrow">{c.eyebrow}</p><h1>{c.title}</h1><p className="lede">{c.lead}</p><div className="button-row"><Link className="button" href={contact}>{c.primary}</Link><Link className="button button-ghost" href={service}>{c.secondary}</Link></div></div><div className="hero-console"><div className="console-top"><span /><span /><span /><b>VIS_001 / OPPORTUNITY MAP</b></div><div className="console-body"><p>INPUT</p><strong>{locale === "en" ? "Customer requests arrive across 4 disconnected channels" : "Las solicitudes llegan por 4 canales desconectados"}</strong><div className="console-flow"><i>01</i><span>{locale === "en" ? "Map workflow" : "Mapear flujo"}</span><i>02</i><span>{locale === "en" ? "Design controls" : "Diseñar controles"}</span><i>03</i><span>{locale === "en" ? "Pilot & measure" : "Pilotar y medir"}</span></div><p>OUTPUT</p><strong className="aqua">{locale === "en" ? "One accountable operating system" : "Un sistema operativo responsable"}</strong></div></div></div></section>
  <div className="value-strip" id="key-benefits"><div className="shell">{c.strip.map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div></div>
  <section className="shell section" id="features"><p className="eyebrow">{c.serviceEyebrow}</p><h2 className="display-two">{c.serviceTitle}</h2><div className="card-grid">{services.slice(0,6).map((s,i)=><Link className="card" href={s.path[locale]} key={s.id}><div className="card-top"><span className="card-number">{String(i+1).padStart(2,"0")}</span><span className={`service-symbol symbol-${i+1}`} aria-hidden="true" /></div><h3>{s.title[locale]}</h3><p>{s.description[locale]}</p><span className="text-link">{locale === "en" ? "Explore service →" : "Explorar servicio →"}</span></Link>)}</div></section>
  <SystemMap locale={locale} />
  <section className="section blueprints" id="demo-video"><span className="legacy-anchor" id="testimonials" /><div className="shell"><div className="section-heading"><div><p className="eyebrow">{c.blueprintEyebrow}</p><h2 className="display-two">{c.blueprintTitle}</h2></div><p>{c.blueprintLead}</p></div><div className="blueprint-list">{solutions.slice(0,4).map((s,i)=><Link href={s.path[locale]} key={s.id}><span className="blueprint-number">0{i+1}</span><h3>{s.title[locale]}</h3><p>{s.description[locale]}</p><span className="row-arrow" aria-hidden="true">↗</span></Link>)}</div></div></section>
  <section className="shell section process-panel" id="how-it-works"><span className="legacy-anchor" id="pricing" /><span className="legacy-anchor" id="faq" /><p className="eyebrow">{c.processEyebrow}</p><h2>{c.processTitle}</h2><p className="lede">{c.processLead}</p><Link className="text-link" href={locale === "en" ? "/process" : "/es/proceso"}>{locale === "en" ? "See how we work →" : "Ver cómo trabajamos →"}</Link></section>
  <section className="shell section"><p className="eyebrow">{c.insightEyebrow}</p><h2 className="display-two">{c.insightTitle}</h2><div className="insight-grid">{insights.slice(0,3).map((x)=><Link href={x.path[locale]} key={x.id}><span>{readTimeLabel(x, locale)}</span><h3>{x.title[locale]}</h3><p>{x.description[locale]}</p></Link>)}</div></section>
  <section className="shell callout callout-large" id="cta"><div><p className="eyebrow">{locale === "en" ? "Start with the work" : "Empieza por el trabajo"}</p><h2>{c.closer}</h2><p>{c.closerText}</p></div><Link href={contact} className="button">{c.primary}</Link></section>
  </main>; }
