import Link from "next/link";
import { insightServicePath, insightSources, readTimeLabel, relatedInsightIds } from "@/content/insight-meta";
import type { Insight } from "@/content/types";
import { insights } from "@/content/insights";
import { ArticleJsonLd } from "./json-ld";
import { Breadcrumbs } from "./breadcrumbs";

export function InsightsIndex({ locale }: { locale: "en" | "es" }) {
  return <main><section className="page-hero"><div className="shell narrow"><p className="eyebrow">{locale === "en" ? "Insights" : "Recursos"}</p><h1>{locale === "en" ? "Practical guidance for responsible AI implementation" : "Orientación práctica para implementar IA responsable"}</h1><p className="lede">{locale === "en" ? "Clear thinking on use cases, operating models, human oversight and the path from pilot to production." : "Ideas claras sobre casos de uso, modelos operativos, supervisión y el paso de piloto a producción."}</p></div></section><section className="shell insight-list">{insights.map((insight) => <Link href={insight.path[locale]} key={insight.id}><div><span>{insight.publishedAt} · {readTimeLabel(insight, locale)} · {locale === "en" ? "By Viste.ai" : "Por Viste.ai"}</span><h2>{insight.title[locale]}</h2><p>{insight.description[locale]}</p></div><b>↗</b></Link>)}</section></main>;
}

export function InsightArticle({ insight, locale }: { insight: Insight; locale: "en" | "es" }) {
  const sources = insightSources[insight.id] || [];
  const related = (relatedInsightIds[insight.id] || []).map((id) => insights.find((item) => item.id === id)).filter((item): item is Insight => Boolean(item));
  const servicePath = insightServicePath[insight.id]?.[locale] || (locale === "en" ? "/services" : "/es/servicios");
  return <main><ArticleJsonLd insight={insight} locale={locale} /><article><header className="page-hero article-hero"><div className="shell narrow"><Breadcrumbs path={insight.path[locale]} title={insight.title[locale]} locale={locale} /><p className="eyebrow">{insight.publishedAt} · {readTimeLabel(insight, locale)}</p><h1>{insight.title[locale]}</h1><p className="lede">{insight.description[locale]}</p><div className="article-author"><span>V</span><div><strong>Viste.ai</strong><small>{locale === "en" ? "Senior-led implementation company" : "Empresa de implementación dirigida por perfiles senior"}</small></div></div></div></header><div className="shell article-body">{insight.sections[locale].map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets ? <ul>{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul> : null}</section>)}
        <section className="article-sources" aria-labelledby="article-sources-title"><h2 id="article-sources-title">{locale === "en" ? "Sources and further reading" : "Fuentes y lecturas adicionales"}</h2><p>{locale === "en" ? "These primary sources support the governance and implementation principles discussed above. External guidance may change; check the linked publisher for the current version." : "Estas fuentes primarias respaldan los principios de gobierno e implementación. La orientación externa puede cambiar; consulta la versión vigente del editor."}</p><ul>{sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer"><strong>{source.title[locale]}</strong><span>{source.publisher} ↗</span></a></li>)}</ul></section>
      </div></article>
    <section className="shell article-related"><p className="eyebrow">{locale === "en" ? "Continue the decision" : "Continúa la decisión"}</p><h2>{locale === "en" ? "Related guidance" : "Contenido relacionado"}</h2><div>{related.map((item) => <Link href={item.path[locale]} key={item.id}><span>{readTimeLabel(item, locale)}</span><strong>{item.title[locale]}</strong></Link>)}</div></section>
    <section className="shell callout"><div><p className="eyebrow">{locale === "en" ? "From guidance to implementation" : "De la orientación a la implementación"}</p><h2>{locale === "en" ? "Apply this to a real workflow." : "Aplícalo a un flujo real."}</h2><p>{locale === "en" ? "See the relevant service approach, then bring us the workflow, systems and outcome that matter." : "Consulta el servicio relacionado y cuéntanos el flujo, los sistemas y el resultado que importan."}</p></div><Link className="button" href={servicePath}>{locale === "en" ? "View the service" : "Ver el servicio"}</Link></section>
  </main>;
}
